## Знакомство с библиотекой NumPy

Библиотеку NumPy традиционно подключают следующим образом:

In [1]:
import numpy as np

Для создания массива можно использовать [несколько различных методов](https://docs.scipy.org/doc/numpy/user/quickstart.html#array-creation). Сконструировать массив из объекта или объектов языка Python позволяет функция `array`, которой передаётся список (list) (или кортеж — tuple). 

_Замечание_. Используйте клавишу `Tab` для автопродолжения (если Вы забыли название функции и помните лишь начало названия или просто не желаете набирать его полностью, то введите одну-две буквы и нажмите клавишу `Tab`; в открывающемся небольшом окошке появятся возможные продолжения слова, из которых останется выбрать нужное).

In [2]:
a1 = np.array([-1, 2, 17])
display(a1)
2*a1

array([-1,  2, 17])

array([-2,  4, 34])

NumPy позволяет работать с матрицами (двумерными массивами) и массивами бОльших размерностей.

In [3]:
np.array([[2,3], [4,5]])

array([[2, 3],
       [4, 5]])

Вот трёхмерный массив:

In [4]:
a2 = np.array([[[1,2,3], [4,5,6,], [7,8,9]], [[11,12,13], [14,15,16,], [17,18,19]]])
a2

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[11, 12, 13],
        [14, 15, 16],
        [17, 18, 19]]])

In [5]:
display(type(a2))
display(np.shape(a2))

numpy.ndarray

(2, 3, 3)

Функция `shape` позволяет не только узнать форму массива, но и изменить её:

In [6]:
a2.shape = (2, 9)
a2

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9],
       [11, 12, 13, 14, 15, 16, 17, 18, 19]])

Индексация и вырезки (slicing) для массивов работают так же, как для строк и списков:

In [7]:
display(a2[0,3])
display(a2[1:, ::-1])

4

array([[19, 18, 17, 16, 15, 14, 13, 12, 11]])

Часто требуется создать массив с одинаково отстоящими друг от друга элементами.
Для этих целей удобно использовать функции `arange` и `linspace`:

In [8]:
np.arange(0.0, 9.0, 0.5)

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. ,
       6.5, 7. , 7.5, 8. , 8.5])

In [9]:
np.linspace(0.0, 9.0, num = 19, endpoint = True)

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. ,
       6.5, 7. , 7.5, 8. , 8.5, 9. ])

В отличие от списков языка Python «обычные» массивы библиотеки NumPy всегда содержат элементы одного [типа](https://docs.scipy.org/doc/numpy/user/basics.types.html). 

*Структурированные массивы* библиотеки NumPy позволяют обойти это ограничение, но часто лучше не пользоваться этой
возможностью, и при необходимости работать с объектами `DataFrame` библиотеки Pandas.

Если про создании массива в исходном списке содержатся элементы различных типов, то
выполняется так называемое повышающее приведение типов. В нижеприведённом примере целочисленные значения преобразуются в числа с плавающей точкой:

In [10]:
np.array([3.14, 4, 2, 3])

array([3.14, 4.  , 2.  , 3.  ])

Явно указать [тип данных](https://docs.scipy.org/doc/numpy/user/basics.types.html) создаваемого массива позволяет аргумент `dtype`:

In [11]:
np.array([1, -1, 2, -4], dtype = complex)

array([ 1.+0.j, -1.+0.j,  2.+0.j, -4.+0.j])

Вот некоторые иные способы создания массивов специального вида:

In [12]:
np.zeros((3,5)) # все элементы 0

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [13]:
np.ones((2,2,2)) # все элементы 1

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

In [14]:
np.eye(4) # единичная матрица, диагональные элементы равны 1

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

С простейшими операциями над массивами и матрицами можно познакомиться в разделе [Numerical Operations on Numpy Arrays](https://www.python-course.eu/numpy_numerical_operations_on_numpy_arrays.php) руководства Numerical Programming. Рекомендуется копировать оттуда примеры, вставлять их в блокнот и выполнять.

**Обратите внимание на разницу между умножением двумерных массивов и умножением матриц!**


In [15]:
a1 = np.array([[1,2], [3,4]])
a2 = np.array([[10,20], [30, 40]])
a1*a2

array([[ 10,  40],
       [ 90, 160]])

In [16]:
np.dot(a1,a2)

array([[ 70, 100],
       [150, 220]])